/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface KAccordion {
    color: string;
    description: string;
    label: string;
    width: string;
  }
  interface KLabel {
    htmlfor: string;
  }
  interface MyComponent {
    /**
     * The first name
     */
    first: string;
    /**
     * The last name
     */
    last: string;
    /**
     * The middle name
     */
    middle: string;
  }
}
declare global {
  interface HTMLKAccordionElement
    extends Components.KAccordion,
      HTMLStencilElement {}
  var HTMLKAccordionElement: {
    prototype: HTMLKAccordionElement;
    new (): HTMLKAccordionElement;
  };
  interface HTMLKLabelElement extends Components.KLabel, HTMLStencilElement {}
  var HTMLKLabelElement: {
    prototype: HTMLKLabelElement;
    new (): HTMLKLabelElement;
  };
  interface HTMLMyComponentElement
    extends Components.MyComponent,
      HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'k-accordion': HTMLKAccordionElement;
    'k-label': HTMLKLabelElement;
    'my-component': HTMLMyComponentElement;
  }
}
declare namespace LocalJSX {
  interface KAccordion {
    color?: string;
    description?: string;
    label?: string;
    onHandleToggle?: (event: CustomEvent<any>) => void;
    width?: string;
  }
  interface KLabel {
    htmlfor?: string;
  }
  interface MyComponent {
    /**
     * The first name
     */
    first?: string;
    /**
     * The last name
     */
    last?: string;
    /**
     * The middle name
     */
    middle?: string;
  }
  interface IntrinsicElements {
    'k-accordion': KAccordion;
    'k-label': KLabel;
    'my-component': MyComponent;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'k-accordion': LocalJSX.KAccordion &
        JSXBase.HTMLAttributes<HTMLKAccordionElement>;
      'k-label': LocalJSX.KLabel & JSXBase.HTMLAttributes<HTMLKLabelElement>;
      'my-component': LocalJSX.MyComponent &
        JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}
